version: 2

models:
  - name: dim_ticker
    columns:
      - name: ticker_sk
        tests:
          - not_null
          - unique
      - name: symbol
        tests:
          - not_null
          - unique

  - name: dim_time
    columns:
      - name: time_sk
        tests:
          - not_null
          - unique
      - name: timestamp_utc
        tests:
          - not_null

  - name: fct_price_snapshots
    columns:
      - name: ticker_sk
        tests:
          - not_null
      - name: time_sk
        tests:
          - not_null
      - name: price_usd
        tests:
          - not_null
